# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region                   = "eu-north-1"
  shared_credentials_files = "~/.aws/credentials"
  profile                  = "default"
}

provider "gitlab" {
  base_url = "http://gitlab.local/api/v4/"
  token    = "glpat-nHbxJ1L5zMPmyexYbTgg"
}
